# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
       node-version: [12.x, 14.x, 16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
           
      - name: Install dependencies
        run: npm ci
        
      - name: Build and test
        run: |
           npm run build --if-present
           npm test  
           
  deploy:
      needs: build
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build and package
        run: |
          npm run build
          npm run package

      - name: Deploy to production
        run: |
          # Ici, vous pouvez ajouter les commandes nécessaires pour déployer votre application dans un environnement de production
          # Par exemple, vous pouvez utiliser un outil comme Docker pour exécuter votre application dans un conteneur et le déployer sur un serveur

      # Runs a set of commands using the runners shell
     # - name: Run a multi-line script
      #  run: |
       #   echo Add other actions to build,
        #  echo test, and deploy your project.
